In [1]:
# !pip install -U -q PyDrive
# from pydrive.auth import GoogleAuth
# from pydrive.drive import GoogleDrive
# from google.colab import auth
# from oauth2client.client import GoogleCredentials

In [2]:
# auth.authenticate_user()
# gauth = GoogleAuth()
# gauth.credentials = GoogleCredentials.get_application_default()
# drive = GoogleDrive(gauth)

In [3]:
# pip install --upgrade tensorflow

In [4]:
# #https://drive.google.com/file/d/1XclUY4dJp7PnwwWUCILV5AzSvzK-3RYT/view?usp=sharing
# id='1XclUY4dJp7PnwwWUCILV5AzSvzK-3RYT'

import pandas as pd

# downloaded = drive.CreateFile({'id':id}) 
# downloaded.GetContentFile('Merged_All_pc_df.csv')  
df = pd.read_csv('Merged_All_pc_df.csv')

In [5]:
df

,Unnamed: 0,Michael Lehmann,Tim Johnson,Christopher Miller,Louis Leterrier,Raja Gosnell,Steve Oedekerk,Sidney Lumet,Richard Donner,Joel Coen,...,Western,Drama,Classics,Special Interest,Romance,Television,content_rating,runtime,production_company,audience_rating
0,*batteries not included,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,G,106.0,Universal Pictures,64
1,10 Things I Hate About You,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,97.0,Buena Vista,69
2,"10,000 B.C.",0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG-13,109.0,Warner Bros.,37
3,101 Dalmatians,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,79.0,Buena Vista,76
4,101 Dalmatians,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,103.0,Buena Vista,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4344,Zoolander 2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,102.0,Paramount,20
4345,Zootopia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG,108.0,Disney,92
4346,Zulu,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG,135.0,Paramount,91
4347,xXx: Return of Xander Cage,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,PG-13,102.0,Paramount,37
4348,xXx: State of the Union,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,R,100.0,Sony,32

In [6]:
from numpy.random import seed
import numpy as np
import tensorflow
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder, MinMaxScaler
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder

In [7]:
runtime = df["runtime"]
runtime

0       106.0
1        97.0
2       109.0
3        79.0
4       103.0
        ...
4344    102.0
4345    108.0
4346    135.0
4347    102.0
4348    100.0
Name: runtime, Length: 4349, dtype: float64

In [8]:
runtime.min()

8.0

In [9]:
runtime.max()

254.0

In [10]:
runtime = pd.DataFrame(runtime)

In [11]:
df.loc[df["runtime"] <= 90, "runtime"] = 1
df.loc[df["runtime"].between(90,120), "runtime"] = 2
df.loc[df["runtime"] >= 120, "runtime"] = 3

In [12]:
df

,Unnamed: 0,Michael Lehmann,Tim Johnson,Christopher Miller,Louis Leterrier,Raja Gosnell,Steve Oedekerk,Sidney Lumet,Richard Donner,Joel Coen,...,Western,Drama,Classics,Special Interest,Romance,Television,content_rating,runtime,production_company,audience_rating
0,*batteries not included,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,G,2.0,Universal Pictures,64
1,10 Things I Hate About You,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,2.0,Buena Vista,69
2,"10,000 B.C.",0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG-13,2.0,Warner Bros.,37
3,101 Dalmatians,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,1.0,Buena Vista,76
4,101 Dalmatians,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,2.0,Buena Vista,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4344,Zoolander 2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,2.0,Paramount,20
4345,Zootopia,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG,2.0,Disney,92
4346,Zulu,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG,3.0,Paramount,91
4347,xXx: Return of Xander Cage,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,PG-13,2.0,Paramount,37
4348,xXx: State of the Union,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,R,2.0,Sony,32

In [13]:
df = df.dropna().reset_index()
df

,index,Unnamed: 0,Michael Lehmann,Tim Johnson,Christopher Miller,Louis Leterrier,Raja Gosnell,Steve Oedekerk,Sidney Lumet,Richard Donner,...,Western,Drama,Classics,Special Interest,Romance,Television,content_rating,runtime,production_company,audience_rating
0,0,*batteries not included,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,G,2.0,Universal Pictures,64
1,1,10 Things I Hate About You,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,2.0,Buena Vista,69
2,2,"10,000 B.C.",0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG-13,2.0,Warner Bros.,37
3,3,101 Dalmatians,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,1.0,Buena Vista,76
4,4,101 Dalmatians,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,2.0,Buena Vista,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4318,4344,Zoolander 2,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,2.0,Paramount,20
4319,4345,Zootopia,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG,2.0,Disney,92
4320,4346,Zulu,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG,3.0,Paramount,91
4321,4347,xXx: Return of Xander Cage,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,PG-13,2.0,Paramount,37
4322,4348,xXx: State of the Union,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,R,2.0,Sony,32

In [14]:
df = df.drop(columns=["index","Unnamed: 0"])
df

,Michael Lehmann,Tim Johnson,Christopher Miller,Louis Leterrier,Raja Gosnell,Steve Oedekerk,Sidney Lumet,Richard Donner,Joel Coen,Richard Fleischer,...,Western,Drama,Classics,Special Interest,Romance,Television,content_rating,runtime,production_company,audience_rating
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,G,2.0,Universal Pictures,64
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,2.0,Buena Vista,69
2,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG-13,2.0,Warner Bros.,37
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,1.0,Buena Vista,76
4,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,G,2.0,Buena Vista,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG-13,2.0,Paramount,20
4319,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,PG,2.0,Disney,92
4320,0,0,0,0,0,0,0,0,0,0,...,0,1,1,0,0,0,PG,3.0,Paramount,91
4321,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,PG-13,2.0,Paramount,37
4322,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,R,2.0,Sony,32

In [15]:
label_encoder_production = LabelEncoder()
le_pc = label_encoder_production.fit(df["production_company"])

label_encoder_rating = LabelEncoder()
le_rating = label_encoder_rating.fit(df["content_rating"])

label_encoder_runtime = LabelEncoder()
le_runtime = label_encoder_runtime.fit(df["runtime"])

In [16]:
oe_style = OneHotEncoder()
oe_results = oe_style.fit_transform(df["production_company"].values.reshape(-1,1))
pc_df = pd.DataFrame(oe_results.toarray(), columns=oe_style.categories_[0])
pc_df = pc_df.astype(int)
pc_df

,20thCenturyFox,A24,AVCO Embassy Pictures,American International Picture,Anchor Bay Entertainment,Apparition,Artisan,Buena Vista,CBS,Columbia Pictures,...,Touchstone Pictures,TriStar Pictures,Trimark Pictures,Turner Entertainment,USA Films,United Artists Pictures,Universal Pictures,Vestron Pictures,Warner Bros.,Yari Film Group
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
3,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4319,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4320,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4321,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4322,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [17]:
oe_style_2 = OneHotEncoder()
oe_results_2 = oe_style.fit_transform(df["content_rating"].values.reshape(-1,1))
cr_df = pd.DataFrame(oe_results_2.toarray(), columns=oe_style.categories_[0])
cr_df = cr_df.astype(int)
cr_df

      G  NC17  NR  PG  PG-13  R
0     1     0   0   0      0  0
1     0     0   0   0      1  0
2     0     0   0   0      1  0
3     1     0   0   0      0  0
4     1     0   0   0      0  0
...  ..   ...  ..  ..    ... ..
4318  0     0   0   0      1  0
4319  0     0   0   1      0  0
4320  0     0   0   1      0  0
4321  0     0   0   0      1  0
4322  0     0   0   0      0  1

[4323 rows x 6 columns]

In [18]:
oe_style_3 = OneHotEncoder()
oe_results_3 = oe_style.fit_transform(df["runtime"].values.reshape(-1,1))
rt_df = pd.DataFrame(oe_results_3.toarray(), columns=oe_style.categories_[0])
rt_df = rt_df.astype(int)
rt_df

      1.0  2.0  3.0
0       0    1    0
1       0    1    0
2       0    1    0
3       1    0    0
4       0    1    0
...   ...  ...  ...
4318    0    1    0
4319    0    1    0
4320    0    0    1
4321    0    1    0
4322    0    1    0

[4323 rows x 3 columns]

In [19]:
full_df = pd.concat([df, pc_df, cr_df, rt_df], axis=1)
full_df

,Michael Lehmann,Tim Johnson,Christopher Miller,Louis Leterrier,Raja Gosnell,Steve Oedekerk,Sidney Lumet,Richard Donner,Joel Coen,Richard Fleischer,...,Yari Film Group,G,NC17,NR,PG,PG-13,R,1.0,2.0,3.0
0,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
3,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,1,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4318,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
4319,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,1,0
4320,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,1
4321,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,1,0
4322,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,1,0

In [20]:
X = full_df.drop(columns=["audience_rating","content_rating","production_company"])
y = full_df[['audience_rating']].values.reshape(-1,1)
print(X.shape, y.shape)

(4323, 491) (4323, 1)

In [21]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

X_train.head()
dim_df=X_train.to_csv('dim_df.csv', index=False)

In [22]:
model = Sequential()
model.add(Dense(units=1500, activation='relu', input_dim=491))
# model.add(Dense(units=1500, activation='relu'))
# model.add(Dense(units=1500, activation='relu'))
# model.add(Dense(units=1000, activation='relu'))
model.add(Dense(units=1, activation='linear'))
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 1500)              738000
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 1501
=================================================================
Total params: 739,501
Trainable params: 739,501
Non-trainable params: 0
_________________________________________________________________

In [23]:
model.compile(optimizer='adam',
              loss='mean_squared_error')

In [24]:
model.fit(
    X_train,
    y_train,
    epochs=100,
    shuffle=True,
    verbose=2
)

Epoch 1/100
102/102 - 1s - loss: 1973.3828
Epoch 2/100
102/102 - 0s - loss: 326.1050
Epoch 3/100
102/102 - 0s - loss: 278.8409
Epoch 4/100
102/102 - 0s - loss: 256.1588
Epoch 5/100
102/102 - 0s - loss: 242.4718
Epoch 6/100
102/102 - 0s - loss: 234.0142
Epoch 7/100
102/102 - 0s - loss: 228.3101
Epoch 8/100
102/102 - 0s - loss: 222.4248
Epoch 9/100
102/102 - 0s - loss: 218.8950
Epoch 10/100
102/102 - 0s - loss: 215.2679
Epoch 11/100
102/102 - 0s - loss: 211.7130
Epoch 12/100
102/102 - 0s - loss: 208.1917
Epoch 13/100
102/102 - 0s - loss: 203.7190
Epoch 14/100
102/102 - 0s - loss: 198.8445
Epoch 15/100
102/102 - 0s - loss: 193.5057
Epoch 16/100
102/102 - 0s - loss: 188.1354
Epoch 17/100
102/102 - 0s - loss: 180.6604
Epoch 18/100
102/102 - 0s - loss: 173.9045
Epoch 19/100
102/102 - 0s - loss: 166.0970
Epoch 20/100
102/102 - 0s - loss: 160.5857
Epoch 21/100
102/102 - 0s - loss: 151.7140
Epoch 22/100
102/102 - 0s - loss: 145.5179
Epoch 23/100
102/102 - 0s - loss: 138.9308
Epoch 24/100
102/102 - 0s - loss: 133.1121
Epoch 25/100
102/102 - 0s - loss: 126.3632
Epoch 26/100
102/102 - 0s - loss: 121.5338
Epoch 27/100
102/102 - 0s - loss: 115.4131
Epoch 28/100
102/102 - 0s - loss: 110.3413
Epoch 29/100
102/102 - 0s - loss: 106.4555
Epoch 30/100
102/102 - 0s - loss: 102.4396
Epoch 31/100
102/102 - 0s - loss: 97.5471
Epoch 32/100
102/102 - 0s - loss: 94.5709
Epoch 33/100
102/102 - 0s - loss: 90.2085
Epoch 34/100
102/102 - 0s - loss: 87.7060
Epoch 35/100
102/102 - 0s - loss: 85.1813
Epoch 36/100
102/102 - 0s - loss: 82.2022
Epoch 37/100
102/102 - 0s - loss: 80.5462
Epoch 38/100
102/102 - 0s - loss: 77.8191
Epoch 39/100
102/102 - 0s - loss: 75.4445
Epoch 40/100
102/102 - 0s - loss: 73.5275
Epoch 41/100
102/102 - 0s - loss: 72.3805
Epoch 42/100
102/102 - 0s - loss: 71.4391
Epoch 43/100
102/102 - 0s - loss: 70.6350
Epoch 44/100
102/102 - 0s - loss: 68.0933
Epoch 45/100
102/102 - 0s - loss: 66.7366
Epoch 46/100
102/102 - 0s - loss: 65.3221
Epoch 47/100
102/102 - 0s - loss: 63.9056
Epoch 48/100
102/102 - 0s - loss: 63.9686
Epoch 49/100
102/102 - 0s - loss: 62.1048
Epoch 50/100
102/102 - 0s - loss: 62.3218
Epoch 51/100
102/102 - 0s - loss: 59.7598
Epoch 52/100
102/102 - 0s - loss: 59.1151
Epoch 53/100
102/102 - 0s - loss: 58.2398
Epoch 54/100
102/102 - 0s - loss: 57.4154
Epoch 55/100
102/102 - 0s - loss: 56.2653
Epoch 56/100
102/102 - 0s - loss: 56.2344
Epoch 57/100
102/102 - 0s - loss: 56.3760
Epoch 58/100
102/102 - 0s - loss: 55.9384
Epoch 59/100
102/102 - 0s - loss: 53.8818
Epoch 60/100
102/102 - 0s - loss: 53.6426
Epoch 61/100
102/102 - 0s - loss: 52.3851
Epoch 62/100
102/102 - 0s - loss: 52.5405
Epoch 63/100
102/102 - 0s - loss: 52.6229
Epoch 64/100
102/102 - 0s - loss: 51.4910
Epoch 65/100
102/102 - 0s - loss: 50.7659
Epoch 66/100
102/102 - 0s - loss: 50.7887
Epoch 67/100
102/102 - 0s - loss: 49.9752
Epoch 68/100
102/102 - 0s - loss: 49.2838
Epoch 69/100
102/102 - 0s - loss: 48.9318
Epoch 70/100
102/102 - 0s - loss: 49.3953
Epoch 71/100
102/102 - 0s - loss: 48.8633
Epoch 72/100
102/102 - 0s - loss: 48.1178
Epoch 73/100
102/102 - 0s - loss: 48.1439
Epoch 74/100
102/102 - 0s - loss: 47.1177
Epoch 75/100
102/102 - 0s - loss: 46.8598
Epoch 76/100
102/102 - 0s - loss: 46.5093
Epoch 77/100
102/102 - 0s - loss: 45.8004
Epoch 78/100
102/102 - 0s - loss: 45.1532
Epoch 79/100
102/102 - 0s - loss: 44.8279
Epoch 80/100
102/102 - 0s - loss: 44.6306
Epoch 81/100
102/102 - 0s - loss: 44.3313
Epoch 82/100
102/102 - 0s - loss: 43.7242
Epoch 83/100
102/102 - 0s - loss: 43.7259
Epoch 84/100
102/102 - 0s - loss: 44.2587
Epoch 85/100
102/102 - 0s - loss: 43.7455
Epoch 86/100
102/102 - 0s - loss: 43.0296
Epoch 87/100
102/102 - 0s - loss: 42.7650
Epoch 88/100
102/102 - 0s - loss: 42.3415
Epoch 89/100
102/102 - 0s - loss: 42.1948
Epoch 90/100
102/102 - 0s - loss: 43.4273
Epoch 91/100
102/102 - 0s - loss: 42.0484
Epoch 92/100
102/102 - 0s - loss: 42.2003
Epoch 93/100
102/102 - 0s - loss: 41.9154
Epoch 94/100
102/102 - 0s - loss: 41.0852
Epoch 95/100
102/102 - 0s - loss: 40.2337
Epoch 96/100
102/102 - 0s - loss: 40.8492
Epoch 97/100
102/102 - 0s - loss: 40.1077
Epoch 98/100
102/102 - 0s - loss: 40.6427
Epoch 99/100
102/102 - 0s - loss: 39.7097
Epoch 100/100
102/102 - 0s - loss: 39.2655

In [25]:
model.predict(X_test.iloc[1].values.reshape(1,-1))

array([[50.033348]], dtype=float32)

In [26]:
y_test[1]

array([49])

In [36]:
model.save("model.h5")

In [28]:
# import pickle

# dump(model, open('model.pkl', 'wb'))

In [29]:
# from pickle import dump

In [30]:
# filename='model.sav'

# pickle.dump(model, open(filename, 'wb'))

In [31]:
# error=[]
# for i in range(0,len(X_test)):
#     error.append(abs(model.predict(X_test.iloc[i].values.reshape(1,-1))-y_test[1]))

In [32]:
# error

In [33]:
# sum(error)/len(error)

In [34]:
# error.sort()

In [35]:
# n=len(error)
# if n % 2 == 0:
#     median1 = error[n//2]
#     median2 = error[n//2 - 1]
#     median = (median1 + median2)/2
# else:
#     median = error[n//2]
# print("Median is: " + str(median))